<?php

return [
    /**
     * Fields definitions for all attributes of the application
     */
    'default' => [
        // Administration
        [
            'name' => 'name',
            'slug' => 'name',
            'label' => 'Name',
            'placeholder' => 'Enter name',
            'component' => 'TextField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'surname',
            'slug' => 'surname',
            'label' => 'Surname',
            'placeholder' => 'Enter surname',
            'component' => 'TextField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'username',
            'slug' => 'username',
            'label' => 'Username',
            'placeholder' => 'Enter username',
            'component' => 'TextField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'password',
            'slug' => 'password',
            'label' => 'Password',
            'placeholder' => 'Enter password',
            'component' => 'PasswordField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'email',
            'slug' => 'email',
            'label' => 'Email',
            'placeholder' => 'Enter email',
            'component' => 'TextField',
            'rules' => 'email',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'active',
            'slug' => 'active',
            'label' => 'Active',
            'placeholder' => 'Active/Inactive',
            'component' => 'BooleanField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'avatar',
            'slug' => 'avatar',
            'label' => 'avatar',
            'placeholder' => 'Select avatar',
            'component' => 'PictureField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'photo',
            'slug' => 'photo',
            'label' => 'Photo',
            'placeholder' => 'Select photo',
            'component' => 'PictureField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'address',
            'slug' => 'address',
            'label' => 'Address',
            'placeholder' => 'Enter address',
            'component' => 'TextField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'phone',
            'slug' => 'phone',
            'label' => 'Phone',
            'placeholder' => 'Enter phone number',
            'component' => 'PhoneField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'gender',
            'slug' => 'gender',
            'label' => 'Gender',
            'placeholder' => 'Select gender',
            'component' => 'SelectField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'company_name',
            'slug' => 'company_name',
            'label' => 'Company',
            'placeholder' => 'Enter company',
            'component' => 'TextField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'industry',
            'slug' => 'industry',
            'label' => 'Industry',
            'placeholder' => 'Enter industry',
            'component' => 'TextField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'notes',
            'slug' => 'notes',
            'label' => 'Notes',
            'placeholder' => 'Enter notes',
            'component' => 'TextAreaField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'about_me',
            'slug' => 'about_me',
            'label' => 'About me',
            'placeholder' => 'Enter about me',
            'component' => 'TextAreaField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'validated',
            'slug' => 'validated',
            'label' => 'Validated',
            'placeholder' => 'Enter validated date',
            'component' => 'DateField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'transportation_card',
            'slug' => 'transportation_card',
            'label' => 'Transportation Card',
            'placeholder' => 'Enter transportation card',
            'component' => 'FilePickerField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'merchandise_insurance',
            'slug' => 'merchandise_insurance',
            'label' => 'Merchandise insurance',
            'placeholder' => 'Enter transportation card',
            'component' => 'FilePickerField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'high_social_security',
            'slug' => 'high_social_security',
            'label' => 'High Social Security',
            'placeholder' => 'Enter high social security',
            'component' => 'FilePickerField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'payment_current',
            'slug' => 'payment_current',
            'label' => 'Payment current',
            'placeholder' => 'Enter payment current',
            'component' => 'FilePickerField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'vehicle_insurance',
            'slug' => 'vehicle_insurance',
            'label' => 'Vehicle insurance',
            'placeholder' => 'Enter vehicle insurance',
            'component' => 'FilePickerField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'itv',
            'slug' => 'itv',
            'label' => 'Itv',
            'placeholder' => 'Enter itv',
            'component' => 'FilePickerField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_transportation_card',
            'slug' => 'end_date_transportation_card',
            'label' => 'End date transportation card',
            'placeholder' => 'Enter end date of transportation card',
            'component' => 'DateField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_merchandise_insurance',
            'slug' => 'end_date_merchandise_insurance',
            'label' => 'End date of merchandise insurance',
            'placeholder' => 'Enter end date of merchandise insurance',
            'component' => 'DateField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_high_social_security',
            'slug' => 'end_date_high_social_security',
            'label' => 'End date of high social security',
            'placeholder' => 'Enter end date of high social security',
            'component' => 'DateField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_vehicle_insurance',
            'slug' => 'end_date_vehicle_insurance',
            'label' => 'End date of vehicle insurance',
            'placeholder' => 'Enter end date of of vehicle insurance',
            'component' => 'DateField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_itv',
            'slug' => 'end_date_itv',
            'label' => 'End date itv',
            'placeholder' => 'Enter end date of itv',
            'component' => 'DateField',
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],


    ]
];
