<?php
return [
    /**
     * Fields definitions for all attributes of the application
     */
    'default' => [
        [
            'name' => 'name',
            'label' => 'Name',
            'placeholder' => 'Enter name',
            'component' => \App\Enums\Components::TextField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'surname',
            'label' => 'Surname',
            'placeholder' => 'Enter surname',
            'component' => \App\Enums\Components::TextField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'username',
            'label' => 'Username',
            'placeholder' => 'Enter username',
            'component' => \App\Enums\Components::TextField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'password',
            'label' => 'Password',
            'placeholder' => 'Enter password',
            'component' => \App\Enums\Components::PasswordField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'email',
            'label' => 'Email',
            'placeholder' => 'Enter email',
            'component' => \App\Enums\Components::TextField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => 'email',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'active',
            'label' => 'Active',
            'placeholder' => 'Active/Inactive',
            'component' => \App\Enums\Components::BooleanField->value,
            'type' => \App\Enums\ComponentTypes::Boolean->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'avatar',
            'label' => 'avatar',
            'placeholder' => 'Select avatar',
            'component' => \App\Enums\Components::AvatarField->value,
            'type' => \App\Enums\ComponentTypes::File->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'photo',
            'label' => 'Photo',
            'placeholder' => 'Select photo',
            'component' => \App\Enums\Components::AvatarField->value,
            'type' => \App\Enums\ComponentTypes::File->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'address',
            'label' => 'Address',
            'placeholder' => 'Enter address',
            'component' => \App\Enums\Components::TextField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'phone',
            'label' => 'Phone',
            'placeholder' => 'Enter phone number',
            'component' => \App\Enums\Components::PhoneField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'gender',
            'label' => 'Gender',
            'placeholder' => 'Select gender',
            'component' => \App\Enums\Components::SelectField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'company_name',
            'label' => 'Company',
            'placeholder' => 'Enter company',
            'component' => \App\Enums\Components::TextField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'industry',
            'label' => 'Industry',
            'placeholder' => 'Enter industry',
            'component' => \App\Enums\Components::TextField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'notes',
            'label' => 'Notes',
            'placeholder' => 'Enter notes',
            'component' => \App\Enums\Components::TextAreaField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'about_me',
            'label' => 'About me',
            'placeholder' => 'Enter about me',
            'component' => \App\Enums\Components::TextAreaField->value,
            'type' => \App\Enums\ComponentTypes::Text->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'validated',
            'label' => 'Validated',
            'placeholder' => 'Enter validated date',
            'component' => \App\Enums\Components::DateField->value,
            'type' => \App\Enums\ComponentTypes::DateTime->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'transportation_card',
            'label' => 'Transportation card',
            'placeholder' => 'Enter transportation card',
            'component' => \App\Enums\Components::FileField->value,
            'type' => \App\Enums\ComponentTypes::File->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'merchandise_insurance',
            'label' => 'Merchandise insurance',
            'placeholder' => 'Enter transportation card',
            'component' => \App\Enums\Components::FileField->value,
            'type' => \App\Enums\ComponentTypes::File->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'high_social_security',
            'label' => 'High social security',
            'placeholder' => 'Enter high social security',
            'component' => \App\Enums\Components::FileField->value,
            'type' => \App\Enums\ComponentTypes::File->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'payment_current',
            'label' => 'Payment current',
            'placeholder' => 'Enter payment current',
            'component' => \App\Enums\Components::FileField->value,
            'type' => \App\Enums\ComponentTypes::File->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'vehicle_insurance',
            'label' => 'Vehicle insurance',
            'placeholder' => 'Enter vehicle insurance',
            'component' => \App\Enums\Components::FileField->value,
            'type' => \App\Enums\ComponentTypes::File->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'itv',
            'label' => 'Itv',
            'placeholder' => 'Enter itv',
            'component' => \App\Enums\Components::FileField->value,
            'type' => \App\Enums\ComponentTypes::File->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_transportation_card',
            'label' => 'End date transportation card',
            'placeholder' => 'Enter end date of transportation card',
            'component' => \App\Enums\Components::DateField->value,
            'type' => \App\Enums\ComponentTypes::Date->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_merchandise_insurance',
            'label' => 'End date of merchandise insurance',
            'placeholder' => 'Enter end date of merchandise insurance',
            'component' => \App\Enums\Components::DateField->value,
            'type' => \App\Enums\ComponentTypes::Date->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_high_social_security',
            'label' => 'End date of high social security',
            'placeholder' => 'Enter end date of high social security',
            'component' => \App\Enums\Components::DateField->value,
            'type' => \App\Enums\ComponentTypes::Date->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_payment_current',
            'label' => 'End date of payment current',
            'placeholder' => 'Enter end date of payment current',
            'component' => \App\Enums\Components::DateField->value,
            'type' => \App\Enums\ComponentTypes::Date->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_vehicle_insurance',
            'label' => 'End date of vehicle insurance',
            'placeholder' => 'Enter end date of of vehicle insurance',
            'component' => \App\Enums\Components::DateField->value,
            'type' => \App\Enums\ComponentTypes::Date->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'end_date_itv',
            'label' => 'End date itv',
            'placeholder' => 'Enter end date of itv',
            'component' => \App\Enums\Components::DateField->value,
            'type' => \App\Enums\ComponentTypes::Date->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ],
        [
            'name' => 'date_of_birth',
            'label' => 'Date of birth',
            'placeholder' => 'End date of birth',
            'component' => \App\Enums\Components::DateField->value,
            'type' => \App\Enums\ComponentTypes::Date->value,
            'rules' => '',
            'options' => "{}",
            'default_value' => '',
        ]


    ]
];
